micronaut:
  application:
    name: service-cliente-kotlin
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    dialect: H2
jpa:
  default:
    properties:
      entity-scan:
        packages:
          - 'br.com.nadson.model'
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
